// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpoeiaukryysnkbdxvsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwb2VpYXVrcnl5c25rYmR4dnN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMTM2MjksImV4cCI6MjA3Mjg4OTYyOX0.wNCRh3bnZoEMfpxIcEEOm4XyXM2DPfL5yUecnFSMvFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});